app_name: "SalesAgent"
app_version: "1.0.0"

url: "https://uat.smartecgr.com/jsf/rfws/oauth/token"
token_method: "POST"
client_id: "MWNmMjIxNWItYjUyMi00MmFkLWE2MzEtNDUwYzlhZjFmODhj"
client_secret: "ZmFmMzM5NzUtOTgxOC00ZDFjLWI1ZTYtNDlkMGY4MTIyZjlj"
username: "MASTER"
password_sha1: "6799a1ea1b3026125917cdd7353542abe03a2753"

default_staff_id: 197
default_cur_id: 3
default_flow_type_id: 5
quotation_standard_unit_mode: "product_price"
sales_order_standard_unit_mode: "product_price"

customer_part_report_id: 102
customer_list_report_id: 103

be_mapping:
  PUS: 7
  SHK: 4
  OHK: 5
  PHK: 6
  SDG: 3
  STH: 8
